# Device ESP32 Basic Configuration
esphome:
  name: $devicename

esp32:
  board: $board
  framework:
    #type: arduino # va bene per tutti gli usi eccetto BLE proxy e tracker
    type: esp-idf # usare con BLE tracker
    version: recommended

preferences:
  flash_write_interval: 90s

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 10min #default 15min
#  encryption:
#    key: !secret api_key

# Enalble Over The Air
ota:
  - platform: esphome
    password: !secret ota_password

binary_sensor:
  - platform: status
    name: "$devicename stato"
  
text_sensor:
  - platform: version
    name: "$devicename esphome version"
    hide_timestamp: true    

switch:
  - platform: restart
    name: "$devicename restart"
    
time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Rome
    servers: 192.168.178.1

sensor:
  - platform: internal_temperature
    name: "temp esp"    
    update_interval: 120s
    id: temp_esp