# Device ESP32 Basic Configuration
esphome:
  name: $devicename
  friendly_name: $ha_name
  area: $ha_area

esp32:
  board: $board
  framework:
    type: arduino # va bene per tutti gli usi eccetto BLE proxy e tracker
    version: recommended

preferences:
  flash_write_interval: 90s

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 10min #default 15min
#  encryption:
#    key: !secret api_key

#web_server:
# port: 80
# auth:
#    username: !secret web_server_username
#    password: !secret web_server_password

# Enalble Over The Air
ota:
  - platform: esphome
    password: !secret ota_password
#  - platform: web_server   

binary_sensor:
  - platform: status
    id: stato
    name: "stato"
    entity_category: diagnostic
  
text_sensor:
  - platform: version
    id: esphome_version
    name: "esphome version"
    hide_timestamp: true   
    entity_category: diagnostic 

sensor:
  - platform: uptime
    id: tempo_uptime
    name: "uptime"
    entity_category: diagnostic
  - platform: internal_temperature
    id: temp_esp
    name: "temperatura chip"    
    update_interval: 120s
    entity_category: diagnostic    

switch:
  - platform: restart
    id: restart_switch
    name: "restart"
    entity_category: diagnostic


    