# Device esp8266 Basic Configuration
esphome:
  name: $devicename
  friendly_name: $ha_name
  area: $ha_area

esp8266:
  board: $board
  framework:
    version: recommended
  board_flash_mode: dout 
  restore_from_flash: true 

preferences:
  flash_write_interval: 90s

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 10min #default 15min
#  encryption:
#    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

binary_sensor:
  - platform: status
    id: stato
    name: "stato"
  
text_sensor:
  - platform: version
    id: esphome_version
    name: "esphome version"
    hide_timestamp: true    

switch:
  - platform: restart
    id: restart_switch
    name: "restart"
    
time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Rome
    servers: 192.168.178.1    