wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #manual_ip:
  #  static_ip: $static_ip
  #  gateway: 192.168.178.1
  #  subnet: 255.255.255.0
  #  dns1: 192.168.178.10
  #  dns2: 8.8.4.4  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap: {}
  domain: .local #default for mDNS, se si usa DHCP è possibile cambiarlo
  reboot_timeout: 10min
  fast_connect: true

captive_portal:

text_sensor:
  - platform: wifi_info
    ip_address:
      id: ip_address
      name: "ip address"
      icon: mdi:ip-network-outline

sensor:
  - platform: wifi_signal
    id: segnale_wifi
    name: "segnale WiFi"
    update_interval: 3600s    
  - platform: uptime
    id: tempo_uptime
    name: "uptime"

