wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2
  ap:
    ssid: "$devicename AP"
    password: !secret wifi_password
  domain: .fritz.box #default è local per mDNS, se si usa DHCP è possibile cambiarlo
  reboot_timeout: 10min
  fast_connect: true

captive_portal:

text_sensor:
  - platform: wifi_info
    ip_address:
      id: ip_address
      name: "ip address"
      icon: mdi:ip-network-outline
      entity_category: diagnostic

sensor:
  - platform: wifi_signal
    id: segnale_wifi
    name: "segnale WiFi"
    update_interval: 3600s
    entity_category: diagnostic    
